"""Added candidate_process_details table

Revision ID: 26cf20b4edbf
Revises: 5ff8e2674509
Create Date: 2025-06-02 09:45:36.236102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cf20b4edbf'
down_revision: Union[str, None] = '5ff8e2674509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_process_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('passport_register_date', sa.Date(), nullable=True),
    sa.Column('passport_register_date_updated_at', sa.DateTime(), nullable=True),
    sa.Column('application_sent_date', sa.Date(), nullable=True),
    sa.Column('application_sent_date_updated_at', sa.DateTime(), nullable=True),
    sa.Column('applied_job', sa.String(), nullable=True),
    sa.Column('applied_job_updated_at', sa.DateTime(), nullable=True),
    sa.Column('office_name', sa.String(), nullable=True),
    sa.Column('office_name_updated_at', sa.DateTime(), nullable=True),
    sa.Column('visa_status', sa.String(), nullable=True),
    sa.Column('visa_status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('medical', sa.String(), nullable=True),
    sa.Column('medical_updated_at', sa.DateTime(), nullable=True),
    sa.Column('agreement', sa.String(), nullable=True),
    sa.Column('agreement_updated_at', sa.DateTime(), nullable=True),
    sa.Column('embassy', sa.String(), nullable=True),
    sa.Column('embassy_updated_at', sa.DateTime(), nullable=True),
    sa.Column('slbfe_approval', sa.Boolean(), nullable=True),
    sa.Column('slbfe_approval_updated_at', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('departure_date_updated_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidate_process_details_id'), 'candidate_process_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_process_details_id'), table_name='candidate_process_details')
    op.drop_table('candidate_process_details')
    # ### end Alembic commands ###
